In [2]:
import pandas as pd

In [11]:
df = pd.read_parquet(
    r"C:\Users\jainv\OneDrive\Desktop\Documents\Projects\SentinelX-SOC\database\CICIDS2017\Bruteforce-Tuesday-no-metadata.parquet"
)

In [4]:
df.head()

,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Fwd Packets Length Total,Bwd Packets Length Total,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,6,1266342,41,44,2664,6954,456,0,64.975609,109.864571,...,32,0.0,0.0,0,0,0.0,0.0,0,0,Benign
1,6,1319353,41,44,2664,6954,456,0,64.975609,109.864571,...,32,0.0,0.0,0,0,0.0,0.0,0,0,Benign
2,6,160,1,1,0,0,0,0,0.000000,0.000000,...,32,0.0,0.0,0,0,0.0,0.0,0,0,Benign
3,6,1303488,41,42,2728,6634,456,0,66.536583,110.129944,...,32,0.0,0.0,0,0,0.0,0.0,0,0,Benign
4,6,77,1,2,0,0,0,0,0.000000,0.000000,...,32,0.0,0.0,0,0,0.0,0.0,0,0,Benign

In [9]:
df.columns

Index(['Protocol', 'Flow Duration', 'Total Fwd Packets',
       'Total Backward Packets', 'Fwd Packets Length Total',
       'Bwd Packets Length Total', 'Fwd Packet Length Max',
       'Fwd Packet Length Min', 'Fwd Packet Length Mean',
       'Fwd Packet Length Std', 'Bwd Packet Length Max',
       'Bwd Packet Length Min', 'Bwd Packet Length Mean',
       'Bwd Packet Length Std', 'Flow Bytes/s', 'Flow Packets/s',
       'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min',
       'Fwd IAT Total', 'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max',
       'Fwd IAT Min', 'Bwd IAT Total', 'Bwd IAT Mean', 'Bwd IAT Std',
       'Bwd IAT Max', 'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags',
       'Fwd URG Flags', 'Bwd URG Flags', 'Fwd Header Length',
       'Bwd Header Length', 'Fwd Packets/s', 'Bwd Packets/s',
       'Packet Length Min', 'Packet Length Max', 'Packet Length Mean',
       'Packet Length Std', 'Packet Length Variance', 'FIN Flag Count',
       'SYN Flag Count', 'RST Flag Count', 'PSH Flag Count', 'ACK Flag Count',
       'URG Flag Count', 'CWE Flag Count', 'ECE Flag Count', 'Down/Up Ratio',
       'Avg Packet Size', 'Avg Fwd Segment Size', 'Avg Bwd Segment Size',
       'Fwd Avg Bytes/Bulk', 'Fwd Avg Packets/Bulk', 'Fwd Avg Bulk Rate',
       'Bwd Avg Bytes/Bulk', 'Bwd Avg Packets/Bulk', 'Bwd Avg Bulk Rate',
       'Subflow Fwd Packets', 'Subflow Fwd Bytes', 'Subflow Bwd Packets',
       'Subflow Bwd Bytes', 'Init Fwd Win Bytes', 'Init Bwd Win Bytes',
       'Fwd Act Data Packets', 'Fwd Seg Size Min', 'Active Mean', 'Active Std',
       'Active Max', 'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max',
       'Idle Min', 'Label'],
      dtype='str')

In [5]:
# Dataset information
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 119522 entries, 0 to 119521
Data columns (total 78 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   Protocol                  119522 non-null  int8
 1   Flow Duration             119522 non-null  int32
 2   Total Fwd Packets         119522 non-null  int16
 3   Total Backward Packets    119522 non-null  int16
 4   Fwd Packets Length Total  119522 non-null  int32
 5   Bwd Packets Length Total  119522 non-null  int32
 6   Fwd Packet Length Max     119522 non-null  int16
 7   Fwd Packet Length Min     119522 non-null  int16
 8   Fwd Packet Length Mean    119522 non-null  float32
 9   Fwd Packet Length Std     119522 non-null  float32
 10  Bwd Packet Length Max     119522 non-null  int16
 11  Bwd Packet Length Min     119522 non-null  int16
 12  Bwd Packet Length Mean    119522 non-null  float32
 13  Bwd Packet Length Std     119522 non-null  float32
 14  Flow Bytes/s              119522 non-null  float64
 15  Flow Packets/s            119522 non-null  float64
 16  Flow IAT Mean             119522 non-null  float32
 17  Flow IAT Std              119522 non-null  float32
 18  Flow IAT Max              119522 non-null  int32
 19  Flow IAT Min              119522 non-null  int32
 20  Fwd IAT Total             119522 non-null  int32
 21  Fwd IAT Mean              119522 non-null  float32
 22  Fwd IAT Std               119522 non-null  float32
 23  Fwd IAT Max               119522 non-null  int32
 24  Fwd IAT Min               119522 non-null  int32
 25  Bwd IAT Total             119522 non-null  int32
 26  Bwd IAT Mean              119522 non-null  float32
 27  Bwd IAT Std               119522 non-null  float32
 28  Bwd IAT Max               119522 non-null  int32
 29  Bwd IAT Min               119522 non-null  int32
 30  Fwd PSH Flags             119522 non-null  int8
 31  Bwd PSH Flags             119522 non-null  int8
 32  Fwd URG Flags             119522 non-null  int8
 33  Bwd URG Flags             119522 non-null  int8
 34  Fwd Header Length         119522 non-null  int32
 35  Bwd Header Length         119522 non-null  int32
 36  Fwd Packets/s             119522 non-null  float32
 37  Bwd Packets/s             119522 non-null  float32
 38  Packet Length Min         119522 non-null  int16
 39  Packet Length Max         119522 non-null  int16
 40  Packet Length Mean        119522 non-null  float32
 41  Packet Length Std         119522 non-null  float32
 42  Packet Length Variance    119522 non-null  float32
 43  FIN Flag Count            119522 non-null  int8
 44  SYN Flag Count            119522 non-null  int8
 45  RST Flag Count            119522 non-null  int8
 46  PSH Flag Count            119522 non-null  int8
 47  ACK Flag Count            119522 non-null  int8
 48  URG Flag Count            119522 non-null  int8
 49  CWE Flag Count            119522 non-null  int8
 50  ECE Flag Count            119522 non-null  int8
 51  Down/Up Ratio             119522 non-null  int8
 52  Avg Packet Size           119522 non-null  float32
 53  Avg Fwd Segment Size      119522 non-null  float32
 54  Avg Bwd Segment Size      119522 non-null  float32
 55  Fwd Avg Bytes/Bulk        119522 non-null  int8
 56  Fwd Avg Packets/Bulk      119522 non-null  int8
 57  Fwd Avg Bulk Rate         119522 non-null  int8
 58  Bwd Avg Bytes/Bulk        119522 non-null  int8
 59  Bwd Avg Packets/Bulk      119522 non-null  int8
 60  Bwd Avg Bulk Rate         119522 non-null  int8
 61  Subflow Fwd Packets       119522 non-null  int16
 62  Subflow Fwd Bytes         119522 non-null  int32
 63  Subflow Bwd Packets       119522 non-null  int16
 64  Subflow Bwd Bytes         119522 non-null  int32
 65  Init Fwd Win Bytes        119522 non-null  int32
 66  Init Bwd Win Bytes        119522 non-null  int32
 67  Fwd Act Data Packets      119522 non-null  int16
 68  Fwd Seg Size Min          119522 non-null  int8
 69  Active Mean               119522 non-null  float32
 70  Active Std                119522 non-null  float32
 71  Active Max                119522 non-null  int32
 72  Active Min                119522 non-null  int32
 73  Idle Mean                 119522 non-null  float32
 74  Idle Std                  119522 non-null  float32
 75  Idle Max                  119522 non-null  int32
 76  Idle Min                  119522 non-null  int32
 77  Label                     119522 non-null  category
dtypes: category(1), float32(22), float64(2), int16(11), int32(21), int8(21)
memory usage: 26.4 MB

In [6]:
# Statistical summary
df.describe()

,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Fwd Packets Length Total,Bwd Packets Length Total,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,Fwd Act Data Packets,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min
count,119522.000000,1.195220e+05,119522.000000,119522.000000,119522.000000,1.195220e+05,119522.000000,119522.000000,119522.000000,119522.000000,...,119522.000000,119522.000000,1.195220e+05,1.195220e+05,1.195220e+05,1.195220e+05,119522.0,1.195220e+05,1.195220e+05,1.195220e+05
mean,11.370501,1.289287e+07,6.848087,7.077718,552.946386,6.478992e+03,189.728853,22.579015,54.501690,57.353958,...,4.076011,25.593297,8.171107e+04,5.500561e+04,1.866060e+05,5.204302e+04,3841960.5,1.466918e+05,3.947934e+06,3.682127e+06
std,5.506331,3.248282e+07,29.882818,43.546298,2856.605414,7.876677e+04,483.941236,33.375422,111.163979,172.068436,...,22.852013,6.400041,7.186327e+05,4.039118e+05,1.127788e+06,6.526001e+05,13117712.0,1.880798e+06,1.341752e+07,1.295311e+07
min,0.000000,-1.300000e+01,1.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00
25%,6.000000,2.220000e+02,2.000000,1.000000,41.000000,6.000000e+00,30.000000,0.000000,15.500000,0.000000,...,0.000000,20.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00
50%,6.000000,3.678800e+04,2.000000,2.000000,70.000000,1.580000e+02,42.000000,6.000000,38.000000,0.000000,...,1.000000,20.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00
75%,17.000000,1.089135e+06,4.000000,3.000000,176.000000,3.730000e+02,72.000000,41.000000,51.000000,21.920311,...,3.000000,32.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00
max,17.000000,1.199999e+08,3119.000000,3635.000000,232349.000000,7.150819e+06,13929.000000,1472.000000,3412.938721,3541.466553,...,2056.000000,60.000000,1.100000e+08,7.050000e+07,1.100000e+08,1.100000e+08,120000000.0,7.050000e+07,1.200000e+08,1.200000e+08

In [6]:
df["Label"].value_counts()

Label
Benign      117566
PortScan      1956
Name: count, dtype: int64

In [7]:
df.isnull().sum().sum()

np.int64(0)

In [9]:
df.dtypes

Protocol                        int8
Flow Duration                  int32
Total Fwd Packets              int16
Total Backward Packets         int16
Fwd Packets Length Total       int32
                              ...
Idle Mean                    float32
Idle Std                     float32
Idle Max                       int32
Idle Min                       int32
Label                       category
Length: 78, dtype: object

In [8]:
df.columns.tolist()

['Protocol',
 'Flow Duration',
 'Total Fwd Packets',
 'Total Backward Packets',
 'Fwd Packets Length Total',
 'Bwd Packets Length Total',
 'Fwd Packet Length Max',
 'Fwd Packet Length Min',
 'Fwd Packet Length Mean',
 'Fwd Packet Length Std',
 'Bwd Packet Length Max',
 'Bwd Packet Length Min',
 'Bwd Packet Length Mean',
 'Bwd Packet Length Std',
 'Flow Bytes/s',
 'Flow Packets/s',
 'Flow IAT Mean',
 'Flow IAT Std',
 'Flow IAT Max',
 'Flow IAT Min',
 'Fwd IAT Total',
 'Fwd IAT Mean',
 'Fwd IAT Std',
 'Fwd IAT Max',
 'Fwd IAT Min',
 'Bwd IAT Total',
 'Bwd IAT Mean',
 'Bwd IAT Std',
 'Bwd IAT Max',
 'Bwd IAT Min',
 'Fwd PSH Flags',
 'Bwd PSH Flags',
 'Fwd URG Flags',
 'Bwd URG Flags',
 'Fwd Header Length',
 'Bwd Header Length',
 'Fwd Packets/s',
 'Bwd Packets/s',
 'Packet Length Min',
 'Packet Length Max',
 'Packet Length Mean',
 'Packet Length Std',
 'Packet Length Variance',
 'FIN Flag Count',
 'SYN Flag Count',
 'RST Flag Count',
 'PSH Flag Count',
 'ACK Flag Count',
 'URG Flag Count',
 'CWE Flag Count',
 'ECE Flag Count',
 'Down/Up Ratio',
 'Avg Packet Size',
 'Avg Fwd Segment Size',
 'Avg Bwd Segment Size',
 'Fwd Avg Bytes/Bulk',
 'Fwd Avg Packets/Bulk',
 'Fwd Avg Bulk Rate',
 'Bwd Avg Bytes/Bulk',
 'Bwd Avg Packets/Bulk',
 'Bwd Avg Bulk Rate',
 'Subflow Fwd Packets',
 'Subflow Fwd Bytes',
 'Subflow Bwd Packets',
 'Subflow Bwd Bytes',
 'Init Fwd Win Bytes',
 'Init Bwd Win Bytes',
 'Fwd Act Data Packets',
 'Fwd Seg Size Min',
 'Active Mean',
 'Active Std',
 'Active Max',
 'Active Min',
 'Idle Mean',
 'Idle Std',
 'Idle Max',
 'Idle Min',
 'Label']

In [9]:
df.isnull().sum().sum()

np.int64(0)

In [10]:
import numpy as np

np.isinf(df.select_dtypes(include=["float64", "int64"])).sum().sum()

np.int64(0)

In [12]:
df.isnull().sum().sum()

np.int64(0)